FROM node:22-alpine3.20

WORKDIR /app/react-ts-todo-app

COPY package.json ./

#RUN npm install/
RUN npm install -g pnpm@latest-10 && pnpm install

COPY ../ .

RUN pnpm run build

CMD ["pnpm", "run", "preview"]
