FROM node:22.13-alpine3.21

WORKDIR /app/react-ts-list-app

COPY package.json ./
RUN npm install -g pnpm@latest-10 && pnpm install

# Copy the application
COPY . .

EXPOSE 5555

# This app run in the internal port 5174, go to README.md
CMD ["pnpm", "run", "build"]


