server:
  port: 3000
  folders:
    in: /home/manuel/mgallegoa/conceptsProbes/java/SpringBatchTasklet/data
    zip: /home/manuel/mgallegoa/conceptsProbes/java/SpringBatchTasklet/data/zip
    unzip: /home/manuel/mgallegoa/conceptsProbes/java/SpringBatchTasklet/data/unzip

spring:
  application:
    name: SpringBatchTasklet
  # datasource:
  #   url: jdbc:mysql://mysql:3306/SpringBatchTaskletdb?CreateDataBaseIfNotExtis=true
  #   username: root
  #   password: manuelpass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  # To enable the batch module - use never for prod
  batch:
    jdbc:
      initialize-schema: always
    # To run the jobs manualy, using REST(JobLauncher) or from CommanLineRunner bean
    job:
      enabled: false
  # To enable the file use in spring
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always
