server:
  port: 3000

spring:
  application:
    name: SpringBatchTasklet
  # datasource:
  #   url: jdbc:mysql://mysql:3306/SpringBatchTaskletdb?CreateDataBaseIfNotExtis=true
  #   username: root
  #   password: manuelpass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
