server:
  port: 3000
spring:
  application:
    name: SpringBatchChunk
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    job:
      enable: true
    jdbc:
      initialize-schema: always
